Avoiding hardcoding check for specific s3 provider
Aws ls command works for checking both path and creds, so removed prior
cred checks.

diff --git a/assets/check b/assets/check
--- a/assets/check
+++ b/assets/check
@@ -31,19 +31,7 @@ encryption_key="$(echo "${payload}" | jq -r '.source.encryption_key // ""')"
 
 # export for `aws` cli
 AWS_ACCESS_KEY_ID=$(echo "$payload" | jq -r '.source.access_key_id')
-if [ -z "${AWS_ACCESS_KEY_ID}" ] || [ "${AWS_ACCESS_KEY_ID}" = "null" ]; then
-  if [ "${endpoint_url#*$minio_identifier}" != "${endpoint_url}" ]; then # if no creds are supplied and endpoint is for minio, exit
-    echo "No access_key_id supplied, needed if accessing minio."
-    exit 1
-  fi
-fi
 AWS_SECRET_ACCESS_KEY=$(echo "$payload" | jq -r '.source.secret_access_key')
-if [ -z "${AWS_SECRET_ACCESS_KEY}" ] || [ "${AWS_SECRET_ACCESS_KEY}" = "null" ]; then
-  if [ "${endpoint_url#*$minio_identifier}" != "${endpoint_url}" ]; then
-    echo "No secret_access_key supplied, needed if accessing minio."
-    exit 1
-  fi
-fi
 
 # Due to precedence rules, must be unset to support AWS IAM Roles.
 if [ -n "${AWS_ACCESS_KEY_ID}" ] && [ -n "${AWS_SECRET_ACCESS_KEY}" ]; then
@@ -77,13 +65,16 @@ if [ "${encryption_key}" != "" ];then
   with_enc=".gpg"
 fi
 
+timeouts="--cli-read-timeout 5 --cli-connect-timeout 5"
+
 echo "Checking path in S3..."
-aws s3 ls "s3://${bucket}/${path}" --endpoint "${endpoint_url}" --no-verify-ssl > /dev/null || echo "Path check exited with code [$?], check path provided exists" && exit 1
+# shellcheck disable=SC2086
+aws ${timeouts} ${endpoint_opt} ${ssl_verification_opt} s3 ls "s3://${bucket}/${path}" > /dev/null || ( echo "Path check failed, check path provided exists and creds are valid." && exit 1 )
 
 # Consider the most recent LastModified timestamp as the most recent version.
 # We don't want options encapsulated in quotes as they are space-separated switches
 # shellcheck disable=SC2086
-version=$(aws ${ssl_verification_opt} s3 ${endpoint_opt} ls --recursive "s3://${bucket}/${path}" | grep "${suffix}${with_enc}\$" | sha1sum | awk '{print $1}')
+version=$(aws ${ssl_verification_opt} ${endpoint_opt} ${timeouts} s3 ls  --recursive "s3://${bucket}/${path}" | grep "${suffix}${with_enc}\$" | sha1sum | awk '{print $1}')
 
 jq -n "[
   {
