Removed exit on invalid path
We have a scenario where there will be an invalid path
after a nuke of an environment. Exit has been removed but have left the
echo to still help troubleshoot if path being invalid is not intentional.

diff --git a/assets/in b/assets/in
--- a/assets/in
+++ b/assets/in
@@ -76,7 +76,7 @@ timeouts="--cli-read-timeout 5 --cli-connect-timeout 5"
 
 echo "Checking path in S3..."
 # shellcheck disable=SC2086
-aws ${endpoint_opt} ${ssl_verification_opt} ${timeouts} s3 ls "s3://${bucket}/${path}" > /dev/null || ( echo "Path check failed, check path provided exists and creds are valid." && exit 1 )
+aws ${endpoint_opt} ${ssl_verification_opt} ${timeouts} s3 ls "s3://${bucket}/${path}" > /dev/null || echo "Path check failed, check path provided exists and creds are valid."
 
 echo "Downloading from S3..."
 # We don't want options encapsulated in quotes as they are space-separated switches
diff --git a/assets/out b/assets/out
--- a/assets/out
+++ b/assets/out
@@ -86,7 +86,7 @@ timeouts="--cli-read-timeout 5 --cli-connect-timeout 5"
 
 echo "Checking path in S3..."
 # shellcheck disable=SC2086
-aws ${endpoint_opt} ${ssl_verification_opt} ${timeouts} s3 ls "s3://${bucket}/${path}" > /dev/null || ( echo "Path check failed, check path provided exists and creds are valid." && exit 1 )
+aws ${endpoint_opt} ${ssl_verification_opt} ${timeouts} s3 ls "s3://${bucket}/${path}" > /dev/null || echo "Path check failed, check path provided exists and creds are valid."
 
 echo "Uploading to S3..."
 options="--exclude='*' --include='*${suffix}${with_enc}' ${delete_flag}"
